import { MarketingHeader } from "@/components/MarketingHeader";
import { MarketingFooter } from "@/components/MarketingFooter";

export default function TermsPage() {
  return (
    <div className="flex flex-col flex-1">
      <MarketingHeader />

      <main className="flex-1">
        <section className="mx-auto max-w-3xl px-6 pt-16 pb-8 sm:pt-20 text-center">
          <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tight text-ink leading-[1.05]">
            Terms of Service
          </h1>
          <p className="mt-4 text-lg text-ink-3">Last updated: 7 September 2026</p>
        </section>

        <section className="mx-auto max-w-3xl px-6 pb-24">
          <div className="rounded-2xl border border-line bg-white p-8 sm:p-10 space-y-8">
            <p className="text-sm text-ink-3 leading-relaxed">
              By using Venn, you agree to these terms.
            </p>

            <div>
              <h2 className="font-bold text-ink text-lg mb-2">The service</h2>
              <p className="text-sm text-ink-3 leading-relaxed">
                Venn is a free tool for planning trips with a group. We collect preferences
                privately and use AI to suggest destinations and accommodation. We are not a
                travel agent, and we do not process payments or bookings directly —
                accommodation bookings happen through third-party sites (e.g. Booking.com),
                subject to their own terms.
              </p>
            </div>

            <div>
              <h2 className="font-bold text-ink text-lg mb-2">Your account</h2>
              <p className="text-sm text-ink-3 leading-relaxed">
                You must provide accurate information when creating an account. You&apos;re
                responsible for keeping your login details secure.
              </p>
            </div>

            <div>
              <h2 className="font-bold text-ink text-lg mb-2">Acceptable use</h2>
              <p className="text-sm text-ink-3 leading-relaxed">
                Don&apos;t use Venn to harass other users, submit false information, or attempt
                to access other users&apos; private data.
              </p>
            </div>

            <div>
              <h2 className="font-bold text-ink text-lg mb-2">AI-generated content</h2>
              <p className="text-sm text-ink-3 leading-relaxed">
                Trip recommendations are generated by AI and may not always be accurate or
                available at the stated price. Always verify details before booking.
              </p>
            </div>

            <div>
              <h2 className="font-bold text-ink text-lg mb-2">Limitation of liability</h2>
              <p className="text-sm text-ink-3 leading-relaxed">
                Venn is provided &quot;as is.&quot; We&apos;re not liable for losses arising
                from trips booked based on Venn&apos;s recommendations, including price
                changes, availability, or third-party booking issues.
              </p>
            </div>

            <div>
              <h2 className="font-bold text-ink text-lg mb-2">Changes</h2>
              <p className="text-sm text-ink-3 leading-relaxed">
                We may update these terms; continued use of Venn after changes means you accept
                the updated terms.
              </p>
            </div>

            <div>
              <h2 className="font-bold text-ink text-lg mb-2">Contact</h2>
              <p className="text-sm text-ink-3 leading-relaxed">
                <a href="mailto:hello@venntravel.co.uk" className="text-brand hover:underline">
                  hello@venntravel.co.uk
                </a>
              </p>
            </div>
          </div>
        </section>
      </main>

      <MarketingFooter />
    </div>
  );
}
